collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.9081632
color:
  saturation: 0.6503759
  brandStrength: 0.5708791
  lightness: 0.4377014
  brandColors:
    - '#E9E6CF'
    - '#171617'
    - '#77391F'
    - '#E93944'
    - '#DFB490'
  rhythmicContrast: 0.3893662
layout_spectrum: 0.5171858
name: Raspberry Jam Guitars
