layout_spectrum: 0.1627282
typography_spectrum: 0.9081632
color:
  saturation: 0.6503759
  lightness: 0.4377014
  brandStrength: 0.5708791
  brandColors:
    - '#E9E6CF'
    - '#171617'
    - '#77391F'
    - '#E93944'
    - '#DFB490'
  rhythmicContrast: 0.3893662
name: Raspberry Jam Guitars
